apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: iotcontainersource
spec:
  template:
    spec:
      containers:
        - image: quay.io/astoycos/iotcontainersource:latest
          name: iotcontainersource
          env:
            - name: POD_NAME
              value: "mypod"
            - name: POD_NAMESPACE
              value: "event-test"
            - name: MESSAGE_URI
              value: "${MESSAGING_HOST}"
            - name: MESSAGE_PORT
              value : "${MESSAGING_PORT}"
            - name: MESSAGE_TYPE
              value: <enmasse message type>
            - name: MESSAGE_TENANT
              value: <enmasse message tenant>
            - name: TLS_CONFIG
              value: <Enmasse tls config> # 0:no tls 1: tls insecure 2: tls secure
            - name: TLS_PATH
              value: "${TLS_CERT}"
            - name: CLIENT_USERNAME
              value: <enmasse client username>
            - name: CLIENT_PASSWORD
              value: <enmasse client password>
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display